[profile.default]
src = "contracts"
out = "out"
script = "scripts"
libs = ["node_modules", "lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "forge-std/=lib/forge-std/src/",
    "ExcessivelySafeCall/=lib/ExcessivelySafeCall/src/"
]
solc = "0.8.17"
optimizer = true
optimizer_runs = 50
# gas_limit = "18446744073709551615"
fs_permissions = [{ access = "read", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
